# Generated by Django 4.0.5 on 2023-09-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('emailid', models.CharField(max_length=30)),
                ('contactno', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ProductModel',
        ),
    ]
