# Generated by Django 3.2.12 on 2023-08-12 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginmodel',
            name='email',
            field=models.CharField(default='demo123@gmail.com', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loginmodel',
            name='fname',
            field=models.CharField(default='demo', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loginmodel',
            name='lname',
            field=models.CharField(default='demo2', max_length=30),
            preserve_default=False,
        ),
    ]
