# Generated by Django 3.2.12 on 2023-08-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0002_auto_20230812_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginmodel',
            name='cpassword',
            field=models.CharField(default='hello', max_length=30),
            preserve_default=False,
        ),
    ]
